export const ACTIONS = {
  ENTER_ACTION: "ENTER",
  DELETE_ACTION: "DELETE",
  SHIFT_ACTION: "SHIFT",
  KEY_ACTION: "KEY",
  BACKSPACE_ACTION: "BACKSPACE",
  SPACE_ACTION: "SPACE",
  REPLACE_ACTION: "REPLACE",
};
